import { CheckCircle2, ClipboardCopy, Download, FileJson2, RotateCw } from "lucide-react";
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import type { AiExportFormat, AiExportResponse } from "@ai-context/contracts";

import { StatePanel } from "@/components/shared/state-panel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import {
  AiExportApiRequestError,
  downloadAiExport,
  getAiExport
} from "@/features/ai-export/api/ai-export-api";
import { triggerDownload } from "@/features/ai-export/utils/download-ai-export";

const FORMAT_OPTIONS: readonly { format: AiExportFormat; label: string }[] = [
  { format: "AI_CONTEXT", label: "AI Context" },
  { format: "MARKDOWN", label: "Markdown" },
  { format: "TEXT", label: "Plain Text" }
];

type AiExportPanelProps = {
  accessToken: string;
  contextId: string;
};

type ExportStatus =
  { kind: "idle" } | { kind: "success"; message: string } | { kind: "error"; message: string };

function exportErrorMessage(error: unknown): string {
  if (error instanceof AiExportApiRequestError) {
    if (error.status === 401) {
      return "Sign in again to export this Context.";
    }

    if (error.status === 403) {
      return "You do not have access to export this Context.";
    }

    if (error.status === 404) {
      return "The selected Context is no longer available.";
    }

    if (error.status === 400) {
      return "The selected export format is not available.";
    }

    return "Unable to generate export. Please try again.";
  }

  return "Network problem. Check your connection and try again.";
}

export function AiExportPanel({ accessToken, contextId }: AiExportPanelProps) {
  const [format, setFormat] = useState<AiExportFormat>("AI_CONTEXT");
  const [status, setStatus] = useState<ExportStatus>({ kind: "idle" });
  const copyMutation = useMutation({
    mutationFn: async () => {
      const exported = await getAiExport(accessToken, { contextId, format });
      await copyToClipboard(exported.content);

      return exported;
    },
    onSuccess: (exported) => {
      setStatus({ kind: "success", message: `Copied ${labelForFormat(exported.format)} export.` });
    },
    onError: (error) => {
      setStatus({
        kind: "error",
        message:
          error instanceof DOMException
            ? "Could not copy the export. Please try again."
            : exportErrorMessage(error)
      });
    }
  });
  const downloadMutation = useMutation({
    mutationFn: async () => {
      const exported = await downloadAiExport(accessToken, { contextId, format });
      triggerDownload(exported);

      return exported;
    },
    onSuccess: () => {
      setStatus({ kind: "success", message: "Download started." });
    },
    onError: (error) => {
      setStatus({ kind: "error", message: exportErrorMessage(error) });
    }
  });
  const isGenerating = copyMutation.isPending || downloadMutation.isPending;

  return (
    <section className="rounded-md border bg-card/70" aria-labelledby="ai-export-title">
      <div className="grid gap-4 px-4 py-4 lg:px-5">
        <div className="min-w-0">
          <div className="mb-2 flex flex-wrap items-center gap-2">
            <Badge tone="neutral">AI Export</Badge>
            <Badge tone="muted">Generated by backend</Badge>
          </div>
          <h2 id="ai-export-title" className="flex items-center gap-2 text-lg font-semibold">
            <FileJson2 className="size-5 text-muted-foreground" />
            AI Export
          </h2>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">
            Take the selected Project Context into external AI tools without changing its verified
            content.
          </p>
        </div>

        <div className="grid gap-3 sm:grid-cols-[minmax(12rem,18rem)_auto] sm:items-end">
          <label className="grid gap-2 text-sm font-medium" htmlFor="ai-export-format">
            Format
            <Select
              id="ai-export-format"
              value={format}
              disabled={isGenerating}
              aria-label="AI export format"
              onChange={(event) => setFormat(event.target.value as AiExportFormat)}
            >
              {FORMAT_OPTIONS.map((option) => (
                <option key={option.format} value={option.format}>
                  {option.label}
                </option>
              ))}
            </Select>
          </label>

          <div className="flex flex-wrap gap-2">
            <Button
              type="button"
              size="sm"
              disabled={isGenerating}
              aria-busy={copyMutation.isPending}
              onClick={() => copyMutation.mutate()}
            >
              {copyMutation.isPending ? <RotateCw className="animate-spin" /> : <ClipboardCopy />}
              {copyMutation.isPending ? "Generating" : "Copy Context"}
            </Button>
            <Button
              type="button"
              size="sm"
              variant="outline"
              disabled={isGenerating}
              aria-busy={downloadMutation.isPending}
              onClick={() => downloadMutation.mutate()}
            >
              {downloadMutation.isPending ? <RotateCw className="animate-spin" /> : <Download />}
              {downloadMutation.isPending ? "Generating" : "Download"}
            </Button>
          </div>
        </div>

        <p className="text-xs text-muted-foreground" aria-live="polite">
          Selected format: {labelForFormat(format)}
        </p>

        {status.kind === "success" ? (
          <StatePanel
            className="p-3"
            description={status.message}
            icon={CheckCircle2}
            title="Export ready"
            tone="success"
          />
        ) : null}

        {status.kind === "error" ? (
          <StatePanel
            className="p-3"
            description={status.message}
            title="Export failed"
            tone="error"
          />
        ) : null}
      </div>
    </section>
  );
}

function labelForFormat(format: AiExportFormat): string {
  const option = FORMAT_OPTIONS.find((item) => item.format === format);

  return option?.label ?? format;
}

async function copyToClipboard(content: AiExportResponse["content"]): Promise<void> {
  await navigator.clipboard.writeText(content);
}
